const kNoteBox = 'note box';
const kToDoBox = 'todo box';
const kImageBox = 'image box';
const kBookBox = 'books box';
const String kTeacherName = 'Yousef Mohamed';
const String kTeacherJob = 'Flutter Devolper';
const String kPhone = '01067954536';
const String kEmail = 'Yo7sef2002@gmail.com';
const String kEmailSubject = 'Stady To Me Project';
